<?php

namespace App\Containers\Documentation\UI\CLI\Commands;

use App\Containers\Documentation\Actions\GenerateAPIDocsAction;
use App\Containers\Documentation\Actions\GetDocsTypesAction;
use App\Containers\Documentation\Actions\ProcessMarkdownTemplatesAction;
use App\Ship\Parents\Commands\ConsoleCommand;

/**
 * Class GenerateApiDocumentationsCommand
 *
 * @author  Mahmoud Zalt  <mahmoud@zalt.me>
 */
class GenerateApiDocumentationsCommand extends ConsoleCommand
{

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = "apidoc:generate";

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = "Generate API Documentations (using API Doc JS)";

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * @param \App\Containers\Documentation\Actions\ProcessMarkdownTemplatesAction $processMarkdownTemplatesAction
     * @param \App\Containers\Documentation\Actions\GetDocsTypesAction             $getDocsTypesAction
     * @param \App\Containers\Documentation\Actions\GenerateAPIDocsAction          $generateAPIDocsAction
     */
    public function handle(
        ProcessMarkdownTemplatesAction $processMarkdownTemplatesAction,
        GetDocsTypesAction $getDocsTypesAction,
        GenerateAPIDocsAction $generateAPIDocsAction
    ) {
        // parse the markdown file.
        $processMarkdownTemplatesAction->run();

        // get docs types that needs to be generated by the user base on this configs.
        $types = $getDocsTypesAction->run();

        // display a message.
        echo "Generating API Documentations " . implode(' & ', $types) . ".\n";

        // for each type, generate docs.
        foreach ($types as $type) {
            $documentationUrls[] = "> {your-domain}/{$generateAPIDocsAction->run($type)}";
        }

        // display a message.
        echo "Done! You can access your API Docs at: \n" . implode("\n", $documentationUrls) . "\n";
    }
}
