/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DashboardLayout: typeof import('./../../../app/Ship/Resources/Vue/Layouts/DashboardLayout.vue')['default']
    HomePage: typeof import('./../../../app/Ship/Resources/Vue/Pages/HomePage.vue')['default']
    InputError: typeof import('./../../../app/Ship/Resources/Vue/Components/InputError.vue')['default']
    TheLogin: typeof import('./../../../app/Containers/AppSection/Authentication/UI/WEB/Pages/TheLogin.vue')['default']
    TheNavigationDrawer: typeof import('./../../../app/Ship/Resources/Vue/Components/TheNavigationDrawer.vue')['default']
    UserPage: typeof import('./../../../app/Containers/AppSection/Authentication/UI/WEB/Pages/UserPage.vue')['default']
  }
}
