/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "passport.token": [],
    "passport.token.refresh": [],
    "passport.tokens.index": [],
    "passport.tokens.destroy": [
        {
            "name": "token_id"
        }
    ],
    "passport.clients.index": [],
    "passport.clients.store": [],
    "passport.clients.update": [
        {
            "name": "client_id"
        }
    ],
    "passport.clients.destroy": [
        {
            "name": "client_id"
        }
    ],
    "passport.scopes.index": [],
    "passport.personal.tokens.index": [],
    "passport.personal.tokens.store": [],
    "passport.personal.tokens.destroy": [
        {
            "name": "token_id"
        }
    ],
    "verification.verify": [
        {
            "name": "user_id"
        },
        {
            "name": "hash"
        }
    ],
    "home-page": [],
    "login": [],
    "login-page": [],
    "logout": [],
    "unauthorized-page": [],
    "private_docs": [],
    "public_docs": [],
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id"
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key"
        },
        {
            "name": "tags"
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": []
}
}
export {};
