<?php

namespace App\Containers\Documentation\Actions;

use Apiato\Core\Foundation\Facades\Apiato;
use App\Containers\Documentation\UI\CLI\Commands\GenerateSwaggerCommand;
use App\Ship\Parents\Actions\Action;

class GenerateSwaggerAction extends Action
{
    public function run(GenerateSwaggerCommand $console): void
    {
        // parse the markdown file.
        Apiato::call('Documentation@RenderTemplatesTask');

        // get docs types that needs to be generated by the user base on his configs.
        $types = Apiato::call('Documentation@GetAllDocsTypesTask');

        $console->info("Generating Swagger/OpenAPI Documentations for (" . implode(' & ', $types) . ")\n");

        // for each type, generate docs.
        $documentationUrls = array_map(function ($type) use ($console) {
            return Apiato::call('Documentation@GenerateSwaggerTask', [$type, $console]);
        }, $types);

        $console->info("Done! You can access your Swagger/OpenAPI JSON schema at: \n" . implode("\n", $documentationUrls));
    }
}
