/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DashboardLayout: typeof import('./../../../Vue/Layouts/DashboardLayout.vue')['default']
    DashboardPage: typeof import('./../../../Vue/Pages/DashboardPage.vue')['default']
    DataTableSearchBox: typeof import('./../../../Vue/Components/DataTableSearchBox.vue')['default']
    DataTableTemplate: (typeof import('@ship/Vue/Components/DataTable/OrganismDataTable.vue'))['default']
    DataTableToolbar: (typeof import('@ship/Vue/Components/DataTable/Molecules/MoleculeDataTableToolbar.vue'))['default']
    HomePage: typeof import('./../../../Vue/Pages/HomePage.vue')['default']
    IndexUsersPage: typeof import('./../../../../../Containers/AppSection/User/UI/WEB/Pages/IndexUsersPage.vue')['default']
    InputError: typeof import('./../../../Vue/Components/InputError.vue')['default']
    MoleculeDataTableToolbar: typeof import('./../../../Vue/Components/DataTable/Molecules/MoleculeDataTableToolbar.vue')['default']
    OrganismDataTable: typeof import('./../../../Vue/Components/DataTable/OrganismDataTable.vue')['default']
    TheLogin: typeof import('./../../../../../Containers/AppSection/Authentication/UI/WEB/Pages/TheLogin.vue')['default']
    TheNavigationDrawer: typeof import('./../../../Vue/Components/TheNavigationDrawer.vue')['default']
  }
}
