<?php

namespace App\Containers\AppSection\Documentation\Actions;

use Apiato\Core\Foundation\Facades\Apiato;
use App\Containers\AppSection\Documentation\UI\CLI\Commands\GenerateApiDocsCommand;
use App\Ship\Parents\Actions\Action;

class GenerateDocumentationAction extends Action
{
    public function run(GenerateApiDocsCommand $console): void
    {
        // parse the markdown file.
        Apiato::call('Documentation@RenderTemplatesTask');

        // get docs types that needs to be generated by the user base on his configs.
        $types = Apiato::call('Documentation@GetAllDocsTypesTask');

        $console->info("Generating API Documentations for (" . implode(' & ', $types) . ")\n");

        // for each type, generate docs.
        $documentationUrls = array_map(static function ($type) use ($console) {
            return Apiato::call('Documentation@GenerateAPIDocsTask', [$type, $console]);
        }, $types);

        $console->info("Done! You can access your API Docs at: \n" . implode("\n", $documentationUrls));
    }
}
