<?php

namespace App\Containers\AppSection\Documentation\Actions;

use Apiato\Core\Abstracts\Actions\Action as AbstractAction;
use App\Containers\AppSection\Documentation\Tasks\GenerateAPIDocsTask;
use App\Containers\AppSection\Documentation\Tasks\GetAllDocsTypesTask;
use App\Containers\AppSection\Documentation\Tasks\RenderApidocJsonTask;
use App\Containers\AppSection\Documentation\Tasks\RenderTemplatesTask;
use App\Containers\AppSection\Documentation\Traits\DocsGeneratorTrait;
use App\Containers\AppSection\Documentation\UI\CLI\Commands\GenerateApiDocsCommand;

class GenerateDocumentationAction extends AbstractAction
{
    use DocsGeneratorTrait;

    public function run(GenerateApiDocsCommand $console): void
    {
        // get docs types that needs to be generated by the user base on his configs.
        $types = app(GetAllDocsTypesTask::class)->run();

        $this->removeOldConfigs();

        foreach ($types as $type) {
            app(RenderApidocJsonTask::class, ['docType' => $type])->run();
        }

        // parse the markdown file.
        app(RenderTemplatesTask::class)->run();

        $console->info('Generating API Documentations for (' . implode(' & ', $types) . ")\n");

        // for each type, generate docs.
        $documentationUrls = array_map(static function ($type) use ($console) {
            return app(GenerateAPIDocsTask::class)->run($type, $console);
        }, $types);

        $console->info("Done! You can access your API Docs at: \n" . implode("\n", $documentationUrls));
    }

    private function removeOldConfigs(): void
    {
        $files = glob($this->getApiDocJsConfigsPath() . '/*');
        foreach ($files as $file) {
            if (is_file($file)) {
                unlink($file);
            }
        }
    }
}
